version: '3.8'

services: 
  ngnix:
    container_name: "proxy"
    build: 
      context: .
      dockerfile: nginx/Dockerfile
    image: nginx:1.18
    ports:
      - "80:80"
      - "443:443"
    networks:
      - grpc-gagarin
#  web:
#    build: ./client
#    image: gagarin-grpc-client:v1
#    ports: 
#      - 3000:3000
#    restart: unless-stopped
#    networks:
#      - grpc-gagarin
  #proxy:
  #  build: ./envoy
  #  image: gagarin-grpc-envoy:v1
  #  ports: 
  #    - 8080:8080
  #  restart: unless-stopped
  #  networks: 
  #    - grpc-gagarin
#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3-arm64
#    ports:
#    - 9200:9200
#    environment:
#      - discovery.type=single-node
  api:
    container_name: "gagarin-api"
#    build: ./backend/Dockerfile.build
    image: gagarin/backend:latest
    command: ./main-linux-arm64
    ports:
      - "9244:9244"
      - "9245:9245"
    restart: unless-stopped
    networks:
       - grpc-gagarin
networks:
 grpc-gagarin:
   driver: bridge